### ISSUE TITLE
Proposal guidelines: pre-proposal checklist

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#848]
**Outdated**: see [checklist](https://github.com/decred/dcrdocs/issues/848#issuecomment-471795670) below.

After some consideration I believe the following is a good way to run pre-proposals:

* Draft a Markdown document and host it on gist.github.com
  * gists are easy to use, have versions, have comments for github users
  * Markdown can be copy-pasted directly into Politeia later
* Submit the gist link to Reddit r/decred
  * Link, not text. So only gist needs to be updated
* Share Reddit or gist link in #proposals and any related rooms (e.g. #marketing)

**Comment by xaur** [comment]
These recommendations need more thinking. Following [this discussion](https://github.com/xaur/decred-issues/issues/117) publishing proposals on Politeia sooner could increase its engagement. Having realized that, I suggest to remove the "Reddit round" from recommendations and minimize the amount of discussion outside Politeia. Perhaps the initial gist/github round can stay to let a small group of people collaborate on the initial draft.

**Comment by xaur** [comment]
After some observation and thinking about omissions I propose the following recommended checklist of actions (that now spans beyond pre-proposals and covers most of the lifecycle):

- [ ] write pre-proposal in Markdown and post it as [gist](https://gist.github.com/)
- [ ] share draft in #proposals room
- [ ] minimize initial review round, minimize discussion not recorded on Politeia - people who commented on chat/Reddit are less likely to re-post their comments on Politeia
- [ ] publish on Politeia, try to include any useful info generated during pre-proposal discussion outside Politeia
- [ ] pre-vote promotion: in #proposals, in rooms relevant to domain, tweet from your twitter account, ask in #social_media or #proposals to retweet. Remember: if you don't promote your proposal, it may happen that nobody will!
- [ ] let it hang on Politeia long enough to collect feedback, recommended minimum 10-14 days, longer for bigger budget and impact
- [ ] edit the proposal in response to feedback, all edits will be recorded on Politeia
- [ ] promote after you authorized vote
- [ ] promote mid vote or 1-2 days before finish
- [ ] if the vote was successful, keep the community updated on how the work is progressing. Long tedious reports are often not necessary, but a few words every couple weeks is so much better than silence
- [ ] if the vote failed, study why and optionally adjust and try again

**Comment by xaur** [comment]
- [ ] never assume a lot of people read chats

**Comment by xaur** [comment]
I expanded the checklist here: https://github.com/xaur/notes/blob/master/proposal-process.md

**Comment by xaur** [comment]
The checklist above was significantly extended and moved here: https://github.com/decredcommunity/guidelines/blob/master/proposals.md

I think we can close this issue and redirect people to the new location. Also, dcrdocs are welcome to integrate any parts of the new document.
